apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-tool
  labels:
    app: net-tool
spec:
  replicas: 4
  selector:
    matchLabels:
      app: net-tool
  template:
    metadata:
      labels:
        app: net-tool
    spec:
      containers:
      - name: net-tool
        image: praqma/network-multitool
        ports:
        - containerPort: 80
